spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8762

eureka:
  instance:
    hostname: host
  client:
    # 表示是否将自己注册到Eureka,因为要构建集群环境，需要将自己注册到集群中，所以需要开启
    registerWithEureka: true
    # 表示是否从Eureka 获取注册信息，如果是单一节点，不需要同步其他Eureka节点，设置为false。否则集群的话需要将其设置为true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://ip:${server.port}/eureka/,http://ip:${server.port}/eureka/,http://ip:${server.port}/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info